### PR TITLE
Fix codecov

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Hi @royfrancis,

Thanks for you useful package. And great to see how well tested it is! 

I did see codecov was 98.5%, so I decided to make it perfect :-)

As the project does not support RStudio (I think something like `usethis::use_r_studion()` would fix that), I programmed blind. As far as I could see, no test could trigger the functions' code, hence it was dead code. I removed the dead code.

Cheers, Richel

### CODE REVIEW

**Comment by royfrancis** [comment]
Thanks for the input @richelbilderbeek It's not dead code. It's fallback in case no version info is found in the lockfile. If the code coverage is bothering you, I can fix it :) It's just a matter of providing an example lockfile with missing info. I just didn't get around to it.

**Comment by richelbilderbeek** [comment]
Sure, I just wonder how the part behind `!is.null` can ever be reached: you already checked for it not being `NULL`:

```r
get_version_r <- function(x) {
  if (!is.rt(x)) stop("Input must be a single rt_tibble (tibble) or a single rt_list (list) item.") # Check if not NULL
  if (is.rt_tibble(x)) x <- tbl_to_list(x)

  if (!is.null(x$R$Version)) {
    return(x$R$Version)
  } else {
    return(NA) # Can hence never be triggered
  }
}
```

If I thought it would be reachable, I'd have added a test :-) . What am I missing?

**Comment by royfrancis** [comment]
I am not sure if I understand. So consider this function (just using the relevant part):

```r
fn <- function(x){
  if (!is.null(x)) {
    return(x)
  } else {
    return(NA)
  }
}
```

```r
r$> fn("bla")
[1] "bla"

r$> fn(NULL)
[1] NA
```

So, if x is NOT NULL, return it and if x is NULL, then return NA.

Am I missing something?

**Comment by royfrancis** [comment]
Anyhow, I've added a bad lockfile example and added a few more tests and now it's resolved.

**Comment by richelbilderbeek** [comment]
This is great, we agree. 

Great that it's done, well done  :+1:

**Pull request closed without merging**
